services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: commcoach-api-supabase
    environment:
      PYTHONPATH: /app
      # Use Supabase PostgreSQL
      DATABASE_URL: postgresql+psycopg2://postgres:Zeref_0386@db.gardgvamjyyumakmwbey.supabase.co:5432/postgres
      # Supabase Configuration
      SUPABASE_URL: https://gardgvamjyyumakmwbey.supabase.co
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhcmRndmFtanl5dW1ha213YmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1OTY5MTksImV4cCI6MjA3NTE3MjkxOX0.r8fYFmNe9fQ_PvVcMr2xTO0YE7qlG0CH5VQq-q44O-0
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhcmRndmFtanl5dW1ha213YmV5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTU5NjkxOSwiZXhwIjoyMDc1MTcyOTE5fQ.kJLeKhLS5vk2IhzEmZ7xUBVHoQj3LLABw6_IDh8FN0Y
      SUPABASE_JWKS_CACHE_SECONDS: 86400
      # Gemini AI
      GEMINI_API_KEY: AIzaSyB9xShk0ST4KHiQgI0eePWVz8PXgkv4bz0
      GEMINI_MODEL: gemini-1.5-pro-latest
      GEMINI_STT_ENABLED: true
      GEMINI_TTS_ENABLED: true
      # Other APIs
      NEWS_API_KEY: f7a67b3f1e5e4b6c83a4ace3a7370d8f
      WIKIPEDIA_ENABLED: true
      # Audio Processing
      MAX_AUDIO_SIZE_MB: 10
      SUPPORTED_AUDIO_FORMATS: wav,mp3,m4a,ogg
      # CORS
      API_ORIGINS: http://localhost:3000,http://localhost:8080
      COMMCOACH_ENV: production
      # Override any inherited variables to prevent validation errors
      PROVIDER_LLM: ""
      GROQ_API_KEY: ""
      OPENAI_API_KEY: ""
      HF_TOKEN: ""
      JWT_SECRET: ""
    ports:
      - "8000:8000"
    # Start API without migrations for now
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - api_data:/app/data
    restart: unless-stopped

volumes:
  api_data:
