[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
buildContext   = "backend"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT}"
healthcheckPath = "/health"
